version: '3'

services:
  rop_revenge:
    build: ./
    volumes:
      - ./share:/home/rop_revenge:ro
      - ./xinetd:/etc/xinetd.d/rop_revenge:ro
    ports:
      - "30007:10101"
    expose:
      - "10101"
